---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Customer Factory - Creates required aws resources for EKS control plane'

Parameters:
  NetworkStack:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /eks/customer-account-factory/network-stack

Resources:
  ControlPlaneSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Cluster communication with worker nodes
      VpcId:
        Fn::ImportValue: !Sub ${NetworkStack}-VPCID

  SSMControlPlaneSecurityGroup:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/eks/customer-account-factory/control-plane-security-group-id'
      Type: String
      Value: !Ref ControlPlaneSecurityGroup

  ControlPlaneServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - eks.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSServicePolicy

  SSMControlPlaneServiceRole:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/eks/customer-account-factory/control-plane-service-role-arn'
      Type: String
      Value: !GetAtt ControlPlaneServiceRole.Arn

  ControlPlaneUserRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: '/'

  SSMControlPlaneUserRole:
    Type: AWS::SSM::Parameter
    Properties:
      Name: '/eks/customer-account-factory/control-plane-user-role-arn'
      Type: String
      Value: !GetAtt ControlPlaneUserRole.Arn

  ControlPlaneUserPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: user-policy
      Roles:
        - !Ref ControlPlaneUserRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
              - logs:DescribeLogStreams
            Resource:
              - arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
              - route53:Update*
              - route53:List*
              - route53:Get*
              - route53:ChangeResourceRecordSets*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - s3:DeleteObject*
              - s3:Get*
              - s3:List*
              - s3:PutObj*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - ecr:Describe*
              - ecr:Get*
              - ecr:List*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - acm:Describe*
              - acm:Get*
              - acm:List*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - ssm:Describe*
              - ssm:Get*
              - ssm:List*
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DeleteNetworkInterface
            Resource:
              - '*'
          - Effect: Allow
            Action:
              - iam:DetachRolePolicy
              - iam:AttachRolePolicy
              - iam:PassRole
            Resource:
              - '*'
          - Effect: "Allow"
            Action:
              - eks:*
            Resource: "*"

Outputs:
  VpcId:
    Value:
      Fn::ImportValue: !Sub "${NetworkStack}-VPCID"
  SecurityGroups:
    Value: !Join [ ",", [ !Ref ControlPlaneSecurityGroup ] ]
  ServiceRole:
    Value: !GetAtt ControlPlaneServiceRole.Arn
  UserRole:
    Value: !GetAtt ControlPlaneUserRole.Arn
